<?php
function fraiChevrerie_scripts()
{
    wp_enqueue_style(
        'fraiChevrerie_app_css',
        get_theme_file_uri('/public/css/app.css'),
        ['fraiChevrerie_vendor_css'],
        '1.0.0'
    );
    wp_enqueue_style(
        'fraiChevrerie_vendor_css',
        get_theme_file_uri('/public/css/vendor.css'),
        [],
        '1.0.0'
    );
    wp_enqueue_script(
        'fraiChevrerie_app_js',
        get_theme_file_uri('/public/js/app.js'),
        ['fraiChevrerie_vendor_js'],
        '1.0.0',
        true
    );
    wp_enqueue_script(
        'fraiChevrerie_vendor_js',
        get_theme_file_uri('/public/js/vendor.js'),
        [],
        '1.0.0',
        true
    );
}
add_action('wp_enqueue_scripts', 'fraiChevrerie_scripts');